# Generated by Django 3.1.5 on 2021-02-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_ID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=15)),
                ('Last_Name', models.CharField(max_length=15)),
                ('ID_Number', models.IntegerField()),
                ('DOB', models.DateField()),
                ('Mobile_Number', models.IntegerField()),
                ('E_mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizers',
            fields=[
                ('Fert_Chem_ID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Fert_Chem_Name', models.CharField(max_length=75)),
                ('Company', models.CharField(max_length=25)),
                ('Expiry_Date', models.DateField()),
                ('Quantity', models.IntegerField()),
                ('Date_of_Purchase', models.DateField()),
                ('Dosage', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('Sales_ID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Product_Sold', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Quantity_Sold', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Sales_Made', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seedlings',
            fields=[
                ('Seedling_ID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Expected_Planting_Date', models.DateField()),
                ('Purchase_Date', models.DateField()),
                ('Quantity', models.IntegerField()),
                ('Crop_type', models.CharField(max_length=30)),
            ],
        ),
    ]
