# Generated by Django 3.1.5 on 2021-02-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Active',
            field=models.BooleanField(default='t'),
            preserve_default=False,
        ),
    ]
