# Generated by Django 3.1.5 on 2021-02-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0002_employee_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Employment_date',
            field=models.DateField(default='2020-03-03'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='Termination_date',
            field=models.DateField(null=True),
        ),
    ]
