# Generated by Django 3.1.5 on 2021-02-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0003_auto_20210216_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Active',
            field=models.CharField(max_length=5),
        ),
    ]
