# Generated by Django 3.1.5 on 2021-02-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0006_auto_20210220_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Termination_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
